#!/usr/bin/env bash
#info about school file
school_path='./school'
if [ -e "$school_path" ];then
    if [ -f "$school_path" ];then
         echo "school file is a regular file"
    fi
    if [ ! -s "$school_path" ];then
        echo "school file is empty"
    else
        echo "school file is not empty"
    fi
    echo "school file exists"
else
    echo "school file does not exist"
fi
