#!/usr/bin/env bash
#info about school file
school_path='./school'
if [ -e "$school_path" ];then
    echo "school file exists"
    if [ ! -s "$school_path" ];then
        echo "school file is empty"
    else
        echo "school file is not empty"
    fi

    if [ -f "$school_path" ];then
        echo "school file is a regular file"
    fi
else
    echo "school file does not exist"
fi
