#!/usr/bin/env bash
#using multiple traps
sudo bash -c "echo $$ > /var/run/myscript.pid"
trap 'echo "I hate the kill command"; rm -f /var/run/myscript.pid; exit' SIGTERM SIGQUIT
trap "Y U no love me?!" SIGINT
while true
do
	echo "To infinity and beyond"
	sleep 2
done
